import { StyleSheet } from "react-native";

export default StyleSheet.create({
  screen: {
    flex: 1,
  },
  ambientLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  ambientCircleTop: {
    position: "absolute",
    top: -110,
    right: -90,
    width: 260,
    height: 260,
    borderRadius: 130,
  },
  ambientCircleBottom: {
    position: "absolute",
    bottom: 80,
    left: -120,
    width: 280,
    height: 280,
    borderRadius: 140,
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  headerTextWrap: {
    flex: 1,
    marginLeft: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  subtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: "600",
  },
  scrollContainer: {
    gap: 12,
    paddingTop: 6,
    paddingBottom: 120,
  },
  sectionCard: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  label: {
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 8,
    letterSpacing: 0.1,
  },
  helperText: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "500",
  },
  textInput: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    borderWidth: 1,
  },
  selectInput: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectValueText: {
    fontSize: 15,
    fontWeight: "600",
    flex: 1,
    paddingRight: 10,
  },
  selectPlaceholderText: {
    fontSize: 15,
    fontWeight: "500",
    flex: 1,
    paddingRight: 10,
  },
  durationRow: {
    flexDirection: "row",
    gap: 8,
  },
  durationInput: {
    flex: 1.7,
  },
  durationButtons: {
    flex: 4,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  durationButton: {
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    minWidth: 60,
  },
  durationButtonText: {
    fontSize: 13,
    fontWeight: "600",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  weekDayChip: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    minWidth: 58,
    alignItems: "center",
  },
  weekDayText: {
    fontSize: 13,
    fontWeight: "700",
  },
  monthDayChip: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  monthDayText: {
    fontSize: 13,
    fontWeight: "700",
  },
  foodRow: {
    flexDirection: "row",
    gap: 10,
  },
  foodButton: {
    flex: 1,
    borderRadius: 13,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
  },
  foodButtonText: {
    fontSize: 14,
    fontWeight: "700",
  },
  timeContainer: {
    marginBottom: 10,
  },
  timeLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  timeButton: {
    borderRadius: 12,
    padding: 13,
    borderWidth: 1,
  },
  timeButtonText: {
    fontSize: 15,
    fontWeight: "600",
  },
  saveBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
  },
  saveButtonWrap: {
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 7,
  },
  saveButton: {
    minHeight: 56,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(6, 10, 20, 0.52)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  modalContainer: {
    borderRadius: 22,
    padding: 18,
    width: "100%",
    maxHeight: "76%",
    borderWidth: 1,
  },
  modalTitle: {
    fontSize: 19,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 16,
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  timePickerColumn: {
    flex: 1,
    alignItems: "center",
  },
  timePickerLabel: {
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 8,
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  timePickerScroll: {
    width: "100%",
    maxHeight: 220,
  },
  timePickerItem: {
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    marginBottom: 6,
  },
  timePickerItemText: {
    fontSize: 16,
    fontWeight: "600",
  },
  timeSeparator: {
    fontSize: 26,
    fontWeight: "800",
    paddingHorizontal: 2,
  },
  optionModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(6, 10, 20, 0.52)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  optionModalCard: {
    width: "100%",
    maxHeight: "72%",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
  },
  optionModalTitle: {
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 10,
    textAlign: "center",
  },
  optionList: {
    gap: 8,
  },
  optionItem: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optionItemText: {
    fontSize: 14,
    fontWeight: "600",
  },
  modalButtonRow: {
    flexDirection: "row",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    borderRadius: 11,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonText: {
    color: "white",
    fontSize: 15,
    fontWeight: "700",
  },
});
